version: 2.1

aliases:
  - &on_master
    context: shardlabs
    filters:
      branches:
        only:
          - master

  - &on_master_after_test_and_build
    <<: *on_master
    requires:
      - test_py_max
      # TMP: rust vm
      # - test_py_max_rust
      - image_build
      - image_build_arm

jobs:
  test_py_max: &test_template
    docker:
      - image: cimg/python:3.9-node
    resource_class: medium
    parallelism: 4
    steps:
      - checkout
      - run:
          # if this was done later (e.g. just before the test) and the file wasn't present, it would fail after all the installation
          name: Check out previous test metadata
          command: |
            jq . "${CIRCLE_INTERNAL_TASK_DATA}/circle-test-results/results.json"
      - run:
          name: Install development tools
          command: ./scripts/install_dev_tools.sh
      - run:
          name: Compile test contracts
          command: ./scripts/compile_contracts.sh
      - run:
          name: Check devnet versions
          command: ./scripts/check_versions.sh
      - run:
          name: Lint
          command: ./scripts/lint.sh
      - run:
          name: Check import sort
          command: ./scripts/check_import_sort.sh
      - run:
          name: Run pytest tests
          parallel: true
          command: |
            mkdir -p test-results
            shopt -s globstar
            SPLIT_BY_CLASS=$(
              circleci tests glob test/**/test*.py |
              sed  "s/\.py//g; s/\//./g" |
              circleci tests split --split-by=timings --timings-type=classname
            )
            TEST_FILES=$(sed "s/\./\//g; s/ /.py /g; s/$/.py/g;" \<<< $SPLIT_BY_CLASS)
            poetry run pytest -s -v --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  # Since cairo-lang 0.11.0, supported py_min and py_max are the same.
  # Uncomment and modify these lines if py_min and py_max stop being the same.
  # test_py_min:
  #   <<: *test_template
  #   docker:
  #     - image: cimg/python: <PY_VERSION> -node

  test_py_max_rust:
    <<: *test_template
    environment:
      STARKNET_DEVNET_CAIRO_VM: "rust"

  package_build_and_publish:
    docker:
      - image: cimg/python:3.9-node # need npm to publish docs
    resource_class: medium
    steps:
      - checkout
      - run: ./scripts/package_build_and_publish.sh

  image_build:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build amd images
          command: ./scripts/image_build.sh
          environment:
            ARCH_SUFFIX: ""
            REMOTE: true

  image_build_arm:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build arm images
          command: ./scripts/image_build.sh
          environment:
            ARCH_SUFFIX: -arm
            REMOTE: ""

  image_push:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Push images
          command: ./scripts/image_push.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test_py_max
      # TMP: rust vm
      # - test_py_max_rust
      - image_build:
          <<: *on_master
      - image_build_arm:
          <<: *on_master
      - package_build_and_publish:
          <<: *on_master_after_test_and_build
      - image_push:
          <<: *on_master_after_test_and_build
